engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .jscsrc
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"