language: node_js

node_js:
  - 7
  - 6

notifications:
  email:
    recipients:
        - harry.sarson@hotmail.co.uk
    on_success: never
    on_failure: always


after_success: 
  npm run compile && 
  npm run istanbul &&
  npm run codecov;
